services:
  encounter-tracker:
    image: ghcr.io/zachauker/5e-encounter-tracker:latest
    build: .
    container_name: encounter-tracker
    ports:
      - "7542:3000"
    volumes:
      - ./data:/data
    environment:
      - DB_PATH=/data/encounter-tracker.db
    labels:
      - "net.unraid.docker.icon=https://game-icons.net/icons/d4af37/000000/1x1/delapouite/dice-twenty-faces-twenty.png"
    networks:
      - oakwoodproxy
    restart: unless-stopped

networks:
  oakwoodproxy:
    external: true
