services:
  encounter-tracker:
    image: ghcr.io/zachauker/5e-encounter-tracker:latest
    container_name: encounter-tracker
    ports:
      - "7542:3000"
    volumes:
      - ./data:/data
    environment:
      - DB_PATH=/data/encounter-tracker.db
    labels:
      - "net.unraid.docker.icon=https://img.icons8.com/?size=100&id=vcao1uuXchDQ&format=png&color=000000"
    networks:
      - oakwoodproxy
    restart: unless-stopped

networks:
  oakwoodproxy:
    external: true
